### ISSUE TITLE
抄袭不可耻吗？ 

### ISSUE THREAD

**Issue by baocaixiong** [messense/tmcpy#1]

**Comment by messense** [comment]
https://github.com/messense/tmcpy/commit/64660bc6c434cca78a6b7a3f967aaf0c04acec3c

你这么介意的话稍后在 readme 上加上这个信息。

**Comment by baocaixiong** [comment]
这不是介意不介意的问题。

**Comment by messense** [comment]
那么你希望怎么处理？
